{include file="header.tpl"}
<div class="dashboard-tab-content" id="depositConfirmation">
    <div class="deposit-confirmation wow fadeInUp" data-wow-duration="0.4s">
        <h4>Deposit Confirmation</h4>
        <div class="table-wrapper">
            <table class="mt-40">
                <thead>
                    <tr>
                        <th colspan="2" class="large">Make Payment</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Plan:</td>
                        <td>2% daily for 15 business days</td>
                    </tr>
                    <tr>
                        <td>Payouts:</td>
                        <td>2% daily for 15 business days</td>
                    </tr>
                    <tr>
                        <td>Principal Return:</td>
                        <td>2% daily for 15 business days</td>
                    </tr>
                    <tr>
                        <td>Early Principal Withdraw:</td>
                        <td>Not available</td>
                    </tr>
                    <tr>
                        <td>Deposit Fee:</td>
                        <td>0.00% + $0.00 (min. $0.00 max. $0.00)</td>
                    </tr>
                    <tr>
                        <td>Deposit Amount:</td>
                        <td>$10000.00</td>
                    </tr>
                    <tr>
                        <td>Fixed rate:</td>
                        <td>1 BTC = $40,000</td>
                    </tr>
                </tbody>
                <tfoot>
                    <tr>
                        <td>BTC Deposit Amount:</td>
                        <td>0.25000000</td>
                    </tr>
                </tfoot>
            </table>
        </div>
        <div class="payment-info text-center mt-40 wow fadeInUp" data-wow-duration="0.4s">
            <p class="text-center">Please send 0.25000000 BTC to
                <span>12GF4ckZS99GcDazuiSiBVWMnGajx8JzL4</span>
            </p>
            <p class="text-center">Order status: <span>Waiting for payment</span></p>
            <img src="dashboard/images/dashboard/qr-code.png" alt="QR Code">
        </div>
    </div>
    <div class="fixed-rate mt-60 wow fadeInUp" data-wow-duration="0.4s">
        <h4>FIXED Rate Explanation:</h4>
        <p>If You invest $10000 in BTC, you invest 0.25 BTC based on our fixed rate (1
            BTC = $40,000).
            Your daily profit in this case is $300.00 during 45 business days period.
            When withdrawing your daily profit you receive 0.007500 BTC to your wallet
            based on the same fixed rate.
            At the end of the term, when withdrawing your principal deposit of $10000,
            you receive your initial 0.25 BTC, not depending on the changes of the
            market rates.</p>
    </div>
    <div class="important-info mt-40 wow fadeInUp" data-wow-duration="0.4s">
        <h4>Important Information:</h4>
        <ol>
            <li>Be careful while making a deposit! The amount and the address should
                match
                the ones that are generated by the system.</li>
            <li>We do not take any fees or hidden commissions from deposits or withdrawals.
            </li>
            <li>The deposit will be created automatically after we receive 3-8
                confirmations.</li>
        </ol>
    </div>
</div>
{include file="footer.tpl"}
